# By default the port is 80 for the host. If there is a specific port that is being used then append it to the host
# Case 1, default port  : default-value="hostname"
# Case 2, specific port : default-value="hostname:1234"
host: ""
username: ""

#Provide password or encryptedPassword and encryptionKey. See the documentation to find about password encryption.
password: ""

encryptedPassword:
encryptionKey:

#Provide information about hosts and vms to monitor.
# "host" will take host name you want to monitor or "*" to monitor all hosts
# "vms" will take vm names in the host specified or "*" to monitor all vms in that host
# "*" will fetch all the available hosts/vms.
hostConfig:
    - host: "host1"
      vms: ["*"]

#Replaces characters in metric name with the specified characters.
# "replace" takes any regular expression
# "replaceWith" takes the string to replace the matched characters
# Note: Please don't try to replace "|" as we use this to separate metric sections.
metricCharacterReplacer:
    - replace: ","
      replaceWith: " "

metricPrefix: "Custom Metrics|vmware|Status|"
