# By default the port is 80/443 ( http/https ) for the host. If there is a specific port that is being used then append it to the host
# Case 1, default port  : default-value="hostname"
# Case 2, specific port : default-value="hostname:1234"
host: "it-vcenter-01.corp.appdynamics.com"

#Escape special characters using "\"
username: "corp\\svc_cs_vsphere"

#Provide password or encryptedPassword and encryptionKey. See the documentation to find about password encryption.
password: "x0zSievq9EDHN9yvazUU"

encryptedPassword:
encryptionKey:

#Provide information about hosts and vms to monitor.
# "host" will take host name you want to monitor or "*" to monitor all hosts
# "vms" will take vm names in the host specified or "*" to monitor all vms in that host
# "*" will fetch all the available hosts/vms.
hostConfig:
    - host: "dfw-esxi-01.corp.appdynamics.com"
      vms: ["*"]
    - host: "dfw-esxi-02.corp.appdynamics.com"
      vms: ["*"]

#Replaces characters in metric name with the specified characters.
# "replace" takes any regular expression
# "replaceWith" takes the string to replace the matched characters
metricCharacterReplacer:
    - replace: ","
      replaceWith: " "

hostThreads: 3
vmThreads: 7

taskSchedule:
    numberOfThreads: 1
    taskDelaySeconds: 50

metricPrefix: "Custom Metrics|vmware|Status|"
