# By default the port is 80/443 ( http/https ) for the host. If there is a specific port that is being used then append it to the host
# Case 1, default port  : default-value="hostname"
# Case 2, specific port : default-value="hostname:1234"
servers:
  # displayName is optional if you are configuring only 1 server. If you are configuring multiple servers, configuring displayName is mandatory.
  # When configured displayName is added to the metric path
  - displayName: ""
    host: ""

    #Escape special characters using "\"
    username: ""

    #Provide password or encryptedPassword and encryptionKey. See the documentation to find about password encryption.
    password:

    encryptedPassword: ""
    encryptionKey: ""

      #Provide information about hosts and vms to monitor.
      # "host" will take host name you want to monitor or "*" to monitor all hosts
      # "vms" will take vm names in the host specified or "*" to monitor all vms in that host
      # "*" will fetch all the available hosts/vms.
    hostConfig:
      - host: "host1"
        vms: ["vm1","vm2"]
      - host: "host2"
        vms: ["*"]

#Replaces characters in metric name with the specified characters. By default extension takes care of replacing "|",":",",".
#Specify any other char you want to replace here.
# "replace" takes any regular expression
# "replaceWith" takes the string to replace the matched characters
#metricPathReplacements:
#    - replace: ","
#      replaceWith: " "

#Configure this based on the number of hosts and vms you want to monitor. You will get "Queue Capacity reached!! Rejecting runnable tasks.. " error if the numberOfThreads is far less than the
# hosts and vms from which the extension has to collect metrics. You will have to increase numberOfThreads in this case.
numberOfThreads: 15

taskSchedule:
  numberOfThreads: 1
  taskDelaySeconds: 60

#This will create this metric in all the tiers, under this path. Please make sure to have a trailing |
#metricPrefix: "Custom Metrics|vmware|Status|"

#This will create it in specific Tier aka Component. Replace <COMPONENT_ID>. Please make sure to have a trailing |.
#To find out the COMPONENT_ID, please see the screen shot here https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java
metricPrefix: "Server|Component:<COMPONENT_ID>|Custom Metrics|vmware|Status|"

# If any of the following fields are not set, the values of the specific fields are set from the system properties of the corresponding fields as specified in the comments.
# If the system properties are not set for the field, then the data is retrieved from machine agent configFile. Please refer to ControllerInfoFactory for more details.
# Values provided here can be overridden if the same field is configured in either controller-info.xml or system properties.
controllerInfo:
  controllerHost: ""  # -Dappdynamics.controller.hostName
  controllerPort:  # -Dappdynamics.controller.port
  controllerSslEnabled: false # -Dappdynamics.controller.ssl.enabled
  enableOrchestration: false # N/A
  uniqueHostId: "" # -Dappdynamics.agent.uniqueHostId
  username: "admin" # -Dappdynamics.agent.monitors.controller.username
  password: "" # -Dappdynamics.agent.monitors.controller.password
  encryptedPassword: "j+0oxTzUtw2xAdaq4UUq/Q==" # -Dappdynamics.agent.monitors.controller.encryptedPassword
  accountAccessKey: "" # -Dappdynamics.agent.accountAccessKey
  account: "" # -Dappdynamics.agent.accountName
  machinePath: "" # -Dappdynamics.machine.agent.hierarchyPath
  simEnabled: false # -Dappdynamics.sim.enabled
  applicationName: "" # -Dappdynamics.agent.applicationName
  tierName: "" # -Dappdynamics.agent.tierName
  nodeName: "" # -Dappdynamics.agent.nodeName

#Encryption key for your controllerInfo password
encryptionKey: "abcd"